name = "seedrsync-bot"
main = "src/worker/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 0 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "seedrsync-db"
database_id = "placeholder"
